### ISSUE TITLE
Vert.x shared STM example/stress test suggestion

### ISSUE THREAD

**Issue by nmcl** [jbosstm/conferences#12]
Would be useful to show the problem that the STM code solves, at least in the stress test. Make a version of the code without STM and show interleaving and data inconsistency?

**Comment by mmusgrov** [comment]
Fixed with commit [3b35a5bb1e6dac6228f8aefb0b3f66d821e73264](https://github.com/jbosstm/conferences/commit/3b35a5bb1e6dac6228f8aefb0b3f66d821e73264)

**Comment by mmusgrov** [comment]
@nmcl The updated READMEs and demonstration code is https://github.com/jbosstm/conferences/tree/master/mucon2017
