### ISSUE TITLE
devoxxUK2017 demo "script" suggestion

### ISSUE THREAD

**Issue by nmcl** [jbosstm/conferences#6]
Add into the README (or maybe we call it a Script?) what the user should be seeing when they do certain things. For example, when issuing the first curl command put the output into the doc?

rorschach:devoxxUK2017 marklittle$ curl -X POST http://localhost:8080/api/theatre/Apollo
{
  "serviceName" : "theatre",
  "threadId" : "vert.x-eventloop-thread-3",
  "message" : "",
  "bookingCount" : 1,
  "altBookingCount" : 0
}

**Comment by nmcl** [comment]
If you agree, I can take a stab at this.

**Comment by nmcl** [comment]
Also is there an implicit "kill the last demo process" between Use Case 1 and Use Case 2?

**Comment by mmusgrov** [comment]
> If you agree, I can take a stab at this.

That is very generous, sounds good, but only if you have the bandwidth.

**Comment by nmcl** [comment]
No problem.
