### ISSUE TITLE
State what URLs syntax means in devoxxuk2017 script

### ISSUE THREAD

**Issue by nmcl** [jbosstm/conferences#7]
Related to https://github.com/jbosstm/conferences/issues/6 it would be good to say what the URL syntax means in the README/script. For some it's easy, but for others ...

curl -X POST http://localhost:8080/api/trip/Apollo/XYZ

... what's XYZ?

I looked in the presentation but it didn't mention it there.

**Comment by mmusgrov** [comment]
Fixed with commit [](https://github.com/jbosstm/conferences/commit/143164a6914e7c6cdd5310f025a01632e1bc8086)
